version: "3.8"

services:

  chat-app:
    build: ./chat-app/
    container_name: "chat-app"
    ports:
      - "7001:7001"
    volumes:
      - ./chat-app:/usr/src/chat-app
    depends_on: 
      - api-gateway
  
  api-gateway:
    build: ./api-gateway/
    container_name: "api-gateway"
    ports:
      - 7000:7000
    volumes:
      - ./api-gateway:/api-gateway/
      - /api-gateway/node_modules
    depends_on:
      - chat-service
      - users-service

  chat-service:
    build: ./chat-service
    container_name: "chat-service"
    ports:
      - 7100:7100
    volumes:
      - ./chat-service:/chat-service/
      - /chat-service/node_modules
    depends_on:
      - chat-service-db

  users-service:
    build: ./users-service/
    container_name: "users-service"
    ports:
      - 7101:7101
    volumes:
      - ./users-service:/users-service/
      - /users-service/node_modules
    depends_on:
      - users-service-db
      
  chat-service-db:
    image: mysql:5.7.20
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
    ports:
      - 7200:3306
    volumes:
      - chat-service-data:/var/lib/mysql

  users-service-db:
    image: mysql:5.7.20
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
    ports:
      - 7201:3306
    volumes:
      - users-service-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    volumes:
      - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    ports:
      - 7300:80
    depends_on:
      - users-service-db
      - chat-service-db


volumes:
    chat-service-data:
    users-service-data: