version: "3.8"

services:

  chat-app:
    build: ./chat-app/
    container_name: "chat-app"
    ports:
      - "7001:7001"
    volumes:
      - ./chat-app:/usr/src/chat-app
  
  api-gateway:
    build: ./api-gateway/
    container_name: "api-gateway"
    ports:
      - 7000:7000
    volumes:
      - ./api-gateway:/api-gateway/
      - /api-gateway/node_modules

  chat-service:
    build: ./chat-service
    container_name: "chat-service"
    ports:
      - 7100:7100
    volumes:
      - ./chat-service:/chat-service/
      - /chat-service/node_modules